# Generated by Django 4.2.7 on 2025-11-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boothslot',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='number_of_spots',
            field=models.PositiveIntegerField(default=0, help_text='Total number of spots available'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per spot', max_digits=10),
        ),
    ]
