# Generated by Django 4.2.7 on 2025-11-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_boothslot_price_event_number_of_spots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='stripe_payment_id',
            field=models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=200),
        ),
    ]
