# Generated by Django 4.2.7 on 2025-12-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_vendorbooking_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbooking',
            name='vendor_name',
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vendorbooking',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
