# Generated by Django 4.2.7 on 2025-12-02 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_vendor_type_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbooking',
            name='vendor_type',
        ),
    ]
