# Generated by Django 4.2.7 on 2025-12-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_vendorbooking_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='vendor_type',
            field=models.CharField(choices=[('regular', 'General Vendor'), ('food', 'Food Truck Vendor')], default='regular', help_text='Type of vendor: General Vendor or Food Truck Vendor', max_length=20),
        ),
    ]
