# Generated by Django 4.2.7 on 2025-12-02 19:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_vendorbooking_vendor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruckBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('social_media_consent', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('photo_consent', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('noise_sensitive', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('sharing_booth', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('booth_partner_instagram', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('stripe_payment_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cuisine_type', models.CharField(help_text='Type of cuisine (e.g., Mexican, Italian, BBQ)', max_length=100)),
                ('food_items', models.TextField(help_text='What types of food will be sold')),
                ('setup_size', models.CharField(blank=True, help_text='Truck size or dimensions', max_length=100)),
                ('generator', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Can bring own quiet generator', max_length=10)),
                ('booth_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bookings', to='bookings.boothslot')),
            ],
            options={
                'verbose_name': 'Food Truck Booking',
                'verbose_name_plural': 'Food Truck Bookings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='GeneralVendorBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('vendor_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('business_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('pronouns', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('social_media_consent', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('photo_consent', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('noise_sensitive', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('sharing_booth', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('booth_partner_instagram', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('stripe_payment_id', models.CharField(blank=True, help_text='Stripe Checkout Session ID', max_length=200)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=200)),
                ('is_paid', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('products_selling', models.TextField(help_text='What products/items will be sold')),
                ('electricity_cord', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Can bring own extension cord', max_length=10)),
                ('booth_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bookings', to='bookings.boothslot')),
            ],
            options={
                'verbose_name': 'General Vendor Booking',
                'verbose_name_plural': 'General Vendor Bookings',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='VendorBooking',
        ),
    ]
