# Generated by Django 4.2.7 on 2025-12-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_foodtruckbooking_generalvendorbooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruckbooking',
            name='noise_sensitive',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='generalvendorbooking',
            name='noise_sensitive',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
