# Generated by Django 5.2.8 on 2026-02-26 03:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_foodtruckbooking_noise_sensitive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boothslot',
            options={'ordering': ['slot_type', 'spot_number']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='number_of_spots',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='boothslot',
            name='slot_type',
            field=models.CharField(choices=[('regular', 'Regular Vendor'), ('food', 'Food Truck')], default='regular', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='food_price',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Price per food truck spot', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='food_spots_available',
            field=models.PositiveIntegerField(default=2, help_text='Current number of food truck spots available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='food_spots_total',
            field=models.PositiveIntegerField(default=2, help_text='Total number of food truck spots available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='regular_price',
            field=models.DecimalField(decimal_places=2, default=35.0, help_text='Price per regular vendor spot', max_digits=10),
        ),
        migrations.AddField(
            model_name='event',
            name='regular_spots_available',
            field=models.PositiveIntegerField(default=24, help_text='Current number of regular vendor spots available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='event',
            name='regular_spots_total',
            field=models.PositiveIntegerField(default=24, help_text='Total number of regular vendor spots available', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='foodtruckbooking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='foodtruckbooking',
            name='event',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bookings', to='bookings.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodtruckbooking',
            name='health_permit',
            field=models.CharField(blank=True, help_text='Health permit number', max_length=100),
        ),
        migrations.AddField(
            model_name='foodtruckbooking',
            name='is_multi_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foodtruckbooking',
            name='multi_date_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodtruckbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('authorized', 'Authorized (Awaiting Approval)'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='foodtruckbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generalvendorbooking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid in dollars', max_digits=10),
        ),
        migrations.AddField(
            model_name='generalvendorbooking',
            name='event',
            field=models.ForeignKey(default=24, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bookings', to='bookings.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalvendorbooking',
            name='is_multi_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generalvendorbooking',
            name='multi_date_group_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='generalvendorbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('authorized', 'Authorized (Awaiting Approval)'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='generalvendorbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='foodtruckbooking',
            name='booth_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bookings', to='bookings.boothslot'),
        ),
        migrations.AlterField(
            model_name='foodtruckbooking',
            name='generator',
            field=models.CharField(blank=True, choices=[('yes', 'Yes - quiet generator'), ('no', 'No - need power hookup'), ('battery', 'Battery/Solar')], help_text='Power source', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodtruckbooking',
            name='noise_sensitive',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no-preference', 'No Preference')], max_length=15),
        ),
        migrations.AlterField(
            model_name='foodtruckbooking',
            name='photo_consent',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='foodtruckbooking',
            name='sharing_booth',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='foodtruckbooking',
            name='social_media_consent',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='generalvendorbooking',
            name='booth_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_bookings', to='bookings.boothslot'),
        ),
        migrations.AlterField(
            model_name='generalvendorbooking',
            name='electricity_cord',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], help_text='Can bring own extension cord', max_length=3),
        ),
        migrations.AlterField(
            model_name='generalvendorbooking',
            name='noise_sensitive',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no-preference', 'No Preference')], max_length=15),
        ),
        migrations.AlterField(
            model_name='generalvendorbooking',
            name='photo_consent',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='generalvendorbooking',
            name='sharing_booth',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='generalvendorbooking',
            name='social_media_consent',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
